=== florianppn/sepahub/backend/src/main/resources/xml/sepa26.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://univ.fr/sepa26"
           xmlns="http://univ.fr/sepa26"
           elementFormDefault="qualified">

    <xs:simpleType name="Max35Text">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="35"/>
            <xs:pattern value="([a-zA-Z0-9\-?:().,'+ ]+(/[a-zA-Z0-9\-?:().,'+ ]+)*)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Max140Text">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="140"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="SeqTpType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="FRST"/>
            <xs:enumeration value="RCUR"/>
            <xs:enumeration value="OOFF"/>
            <xs:enumeration value="FNAL"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NbOfTxsType">
        <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="15"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="AmountType">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
            <xs:totalDigits value="18"/>
            <xs:pattern value="[0-9]{1,15}(\.[0-9]{1,2})?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IBANType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}"/>
            <xs:minLength value="15"/>
            <xs:maxLength value="34"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="BICType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="PartyType">
        <xs:sequence>
            <xs:element name="Nm" type="Max35Text"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="AccountType">
        <xs:sequence>
            <xs:element name="Id">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="IBAN" type="IBANType"/>
                        <xs:element name="Othr">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Id" type="Max35Text"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AgentType">
        <xs:sequence>
            <xs:element name="FinInstnId">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="BIC" type="BICType" minOccurs="0"/>
                        <xs:element name="Othr" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Id" type="Max35Text"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="PmtId" type="Max35Text"/>

    <xs:element name="InstdAmt">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="AmountType">
                    <xs:attribute name="Ccy" type="xs:string" use="required" fixed="EUR"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="DrctDbtTx">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MndtRltdInf">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MndtId" type="Max35Text"/>
                            <xs:element name="DtOfSgntr" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="DbtrAgt" type="AgentType"/>

    <xs:element name="Dbtr" type="PartyType"/>

    <xs:element name="DbtrAcct" type="AccountType"/>

    <xs:element name="RmtInf" type="xs:string"/>

    <xs:element name="DrctDbtTxInf">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PmtId" type="Max35Text"/>
                <xs:element ref="InstdAmt"/>
                <xs:element ref="DrctDbtTx"/>
                <xs:element ref="DbtrAgt"/>
                <xs:element ref="Dbtr"/>
                <xs:element ref="DbtrAcct"/>
                <xs:element ref="RmtInf" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GrpHdr">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MsgId" type="Max35Text"/>
                <xs:element name="CreDtTm" type="xs:dateTime"/>
                <xs:element name="NbOfTxs" type="NbOfTxsType"/>
                <xs:element name="CtrlSum" type="AmountType"/>
                <xs:element name="InitgPty" type="PartyType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="PmtInf">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PmtInfId" type="Max35Text"/>
                <xs:element name="NbOfTxs" type="NbOfTxsType"/>
                <xs:element name="CtrlSum" type="AmountType"/>
                <xs:element name="PmtTpInf">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SvcLvl" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Cd" type="Max35Text"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="LclInstrm" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Cd" type="Max35Text"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="SeqTp" type="SeqTpType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ReqdColltnDt" type="xs:date"/>
                <xs:element name="Cdtr" type="PartyType"/>
                <xs:element name="CdtrAcct" type="AccountType"/>
                <xs:element name="CdtrAgt" type="AgentType"/>
                <xs:element name="CdtrSchmeId" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Id">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="PrvtId">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Othr">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Id" type="Max35Text"/>
                                                                <xs:element name="SchmeNm">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="Prtry" type="Max35Text"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="DrctDbtTxInf" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CstmrDrctDbtInitn">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GrpHdr"/>
                <xs:element ref="PmtInf" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Document">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CstmrDrctDbtInitn"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== florianppn/sepahub/backend/src/main/resources/xml/sepa26-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Document xmlns:p="http://univ.fr/sepa26"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://univ.fr/sepa26 sepa26.xsd">
  <p:CstmrDrctDbtInitn>
    <p:GrpHdr>
      <p:MsgId>MSGID-123456</p:MsgId>
      <p:CreDtTm>2026-09-24T12:00:00</p:CreDtTm>
      <p:NbOfTxs>1</p:NbOfTxs>
      <p:CtrlSum>1000.0</p:CtrlSum>
      <p:InitgPty>
        <p:Nm>Societe SEPAHub</p:Nm>
      </p:InitgPty>
    </p:GrpHdr>
    <p:PmtInf>
      <p:PmtInfId>REF-REMISE-123</p:PmtInfId>
      <p:NbOfTxs>1</p:NbOfTxs>
      <p:CtrlSum>1000.0</p:CtrlSum>
      <p:PmtTpInf>
        <p:SvcLvl>
          <p:Cd>SEPA</p:Cd>
        </p:SvcLvl>
        <p:LclInstrm>
          <p:Cd>CORE</p:Cd>
        </p:LclInstrm>
        <p:SeqTp>RCUR</p:SeqTp>
      </p:PmtTpInf>
      <p:ReqdColltnDt>2026-10-01</p:ReqdColltnDt>
      <p:Cdtr>
        <p:Nm>Societe SEPAHub</p:Nm>
      </p:Cdtr>
      <p:CdtrAcct>
        <p:Id>
          <p:IBAN>FR7610041010050500013M02606</p:IBAN>
        </p:Id>
      </p:CdtrAcct>
      <p:CdtrAgt>
        <p:FinInstnId>
          <p:BIC>BANKFRPPXXX</p:BIC>
        </p:FinInstnId>
      </p:CdtrAgt>
      <p:CdtrSchmeId>
        <p:Id>
          <p:PrvtId>
            <p:Othr>
              <p:Id>FR00ZZZ123456</p:Id>
              <p:SchmeNm>
                <p:Prtry>SEPA</p:Prtry>
              </p:SchmeNm>
            </p:Othr>
          </p:PrvtId>
        </p:Id>
      </p:CdtrSchmeId>
      <p:DrctDbtTxInf>
        <p:PmtId>REF-OPE-AAAA</p:PmtId>
        <p:InstdAmt Ccy="EUR">1000.0</p:InstdAmt>
        <p:DrctDbtTx>
          <p:MndtRltdInf>
            <p:MndtId>MANDAT-NO-55555</p:MndtId>
            <p:DtOfSgntr>2026-01-01</p:DtOfSgntr>
          </p:MndtRltdInf>
        </p:DrctDbtTx>
        <p:DbtrAgt>
          <p:FinInstnId>
            <p:BIC>BANKGBULXXX</p:BIC>
          </p:FinInstnId>
        </p:DbtrAgt>
        <p:Dbtr>
          <p:Nm>Mr Client Dupont</p:Nm>
        </p:Dbtr>
        <p:DbtrAcct>
          <p:Id>
            <p:IBAN>FR763004136210001234567811</p:IBAN>
          </p:Id>
        </p:DbtrAcct>
        <p:RmtInf>Facture service n°1</p:RmtInf>
      </p:DrctDbtTxInf>
    </p:PmtInf>
  </p:CstmrDrctDbtInitn>
</p:Document>
